# Generated by Django 5.2.13 on 2026-05-28 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenttracker',
            name='attendance_percentage',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='absenttracker',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absenttracker',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absenttracker',
            name='notification_status',
            field=models.CharField(choices=[('SMS Pending', 'SMS Pending'), ('Dispatched', 'Dispatched')], default='SMS Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
