# Generated by Django 5.2.13 on 2026-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0003_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenttracker',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
