# Generated by Django 5.2.13 on 2026-06-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0004_absenttracker_admin_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch_id',
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='', max_length=50),
        ),
    ]
