# Generated by Django 5.2.13 on 2026-06-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0005_remove_student_batch_id_student_batch_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('MERN', 'MERN'), ('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('MEAN', 'MEAN'), ('UI/UX', 'UI/UX')], default='MERN', max_length=50),
        ),
    ]
