# Generated by Django 5.2.13 on 2026-06-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0006_alter_student_batch_alter_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenttracker',
            name='attendance_status',
            field=models.CharField(default='Complete', max_length=20),
        ),
    ]
