# Generated by Django 5.2.13 on 2026-05-18 08:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificates/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_proofs/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='student_photos/'),
        ),
    ]
