# Generated by Django 5.2.13 on 2026-05-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='batch',
            field=models.CharField(choices=[('', 'Select Batch'), ('Batch A', 'Batch A'), ('Batch B', 'Batch B'), ('Batch C', 'Batch C')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10),
        ),
    ]
