# Generated by Django 5.2.13 on 2026-05-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
